<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0-windows</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Flow.Launcher.Plugin.RemoteDesktop</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Page Update="Settings\SettingsControl.xaml">
            <Generator>MSBuild:Compile</Generator>
        </Page>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Flow.Launcher.Plugin.RemoteDesktop.Core\Flow.Launcher.Plugin.RemoteDesktop.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Settings\Localization.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Localization.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Settings\Localization.de.resx">
        <DependentUpon>Localization.resx</DependentUpon>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Settings\Localization.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Localization.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="gong-wpf-dragdrop" Version="4.0.0" />
    </ItemGroup>

</Project>
