<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <RootNamespace>Flow.Launcher.Plugin.RemoteDesktop</RootNamespace>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <DebugSymbols>false</DebugSymbols>
        <DebugType>None</DebugType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Flow.Launcher.Plugin" Version="4.4.0"  ExcludeAssets="Runtime" />
    </ItemGroup>

</Project>
