//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flow.Launcher.Plugin.RemoteDesktop.Settings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flow.Launcher.Plugin.RemoteDesktop.Settings.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddAlias {
            get {
                return ResourceManager.GetString("AddAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddOverride {
            get {
                return ResourceManager.GetString("AddOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure a friendly alias for a host (DNS or IP). Both fields are required..
        /// </summary>
        public static string AliasDialogGuide {
            get {
                return ResourceManager.GetString("AliasDialogGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string AliasDialogTitle {
            get {
                return ResourceManager.GetString("AliasDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Alias....
        /// </summary>
        public static string AliasExample {
            get {
                return ResourceManager.GetString("AliasExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias*.
        /// </summary>
        public static string AliasFieldLabel {
            get {
                return ResourceManager.GetString("AliasFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string AliasHeader {
            get {
                return ResourceManager.GetString("AliasHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default User.
        /// </summary>
        public static string DefaultUserFieldLabel {
            get {
                return ResourceManager.GetString("DefaultUserFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Default User.
        /// </summary>
        public static string DefaultUserHint {
            get {
                return ResourceManager.GetString("DefaultUserHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteAlias {
            get {
                return ResourceManager.GetString("DeleteAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteOverride {
            get {
                return ResourceManager.GetString("DeleteOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditAlias {
            get {
                return ResourceManager.GetString("EditAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditOverride {
            get {
                return ResourceManager.GetString("EditOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Host....
        /// </summary>
        public static string HostExample {
            get {
                return ResourceManager.GetString("HostExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host*.
        /// </summary>
        public static string HostFieldLabel {
            get {
                return ResourceManager.GetString("HostFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string HostHeader {
            get {
                return ResourceManager.GetString("HostHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g.: ^PC.*$.
        /// </summary>
        public static string RegexExample {
            get {
                return ResourceManager.GetString("RegexExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Pattern*.
        /// </summary>
        public static string RegexFieldLabel {
            get {
                return ResourceManager.GetString("RegexFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Pattern.
        /// </summary>
        public static string RegexHeader {
            get {
                return ResourceManager.GetString("RegexHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System User.
        /// </summary>
        public static string SystemUserHint {
            get {
                return ResourceManager.GetString("SystemUserHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter User....
        /// </summary>
        public static string UserExample {
            get {
                return ResourceManager.GetString("UserExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserFieldLabel {
            get {
                return ResourceManager.GetString("UserFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserHeader {
            get {
                return ResourceManager.GetString("UserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to override the user for a new connection, first enter the regex to match the host name or ip address. Once that is done you can specify which user to use. If you leave the user field empty, the current system user is used..
        /// </summary>
        public static string UserOverrideDialogGuide {
            get {
                return ResourceManager.GetString("UserOverrideDialogGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Override.
        /// </summary>
        public static string UserOverrideDialogTitle {
            get {
                return ResourceManager.GetString("UserOverrideDialogTitle", resourceCulture);
            }
        }
    }
}
