name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - src/**
  pull_request:
    branches: [ "main" ]
    paths:
      - src/**

env:
  PROJECT_PATH: ./src/Flow.Launcher.Plugin.RemoteDesktop.sln

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore