name: Publish Release

on:
  workflow_dispatch: 
    inputs:
      version:
        description: '<major>.<minor>.<patch>-<pre-release>'
        type: string
        required: true

permissions:
  contents: write
  
env:
  DOTNET_VERSION: 10.0.x
  ZIP_FOLDER: publish
  ZIP_NAME: remote-desktop-v${{ github.event.inputs.version }}.zip
  VERSION_WITH_V: v${{ github.event.inputs.version }}
  VERSION_NO_V: ${{ github.event.inputs.version }}

jobs:
  pre-release-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Tag
        id: check-tag
        env:
            TAG: ${{ env.VERSION_NO_V }}
        run: |
          echo "Validating semantic version: ${TAG}"
          echo "${TAG}" | grep -P '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-((0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$'

  release:
    if: github.repository == 'XDFUN/Flow.Launcher.Plugin.RemoteDesktop'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set plugin version
        shell: pwsh
        run: |
          $file = "plugin.json"
          $json = Get-Content $file -Raw | ConvertFrom-Json

          $json | Add-Member -NotePropertyName "Version" -NotePropertyValue "${{ env.VERSION_NO_V }}"

          $json | ConvertTo-Json -Depth 10 | Set-Content $file

      - name: Publish
        run: dotnet publish Flow.Launcher.Plugin.RemoteDesktop -c Release -r win-x64 --no-self-contained -p:Version="${{ env.VERSION_NO_V }}" --output "${{ env.ZIP_FOLDER }}" -bl:publish.binlog

      - name: Zip Publish
        run: tar -a -cf "${{ env.ZIP_NAME }}" -C "${{ env.ZIP_FOLDER }}" *

      - name: Upload Diagnostics
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: diagnostics.binlog
          path: publish.binlog

      - name: git-cliff - Changelog Generator
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: -l --sort newest --offline
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Create the Github Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ env.VERSION_WITH_V }}" --repo="${{ github.repository }}" --title="${{ env.VERSION_WITH_V }}" --notes-file "CHANGELOG.md"

      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${{ env.VERSION_WITH_V }}" ${{ env.ZIP_NAME }} --clobber